version: '3'
services:
  
  database:
    image: timescale/timescaledb:latest
    ports: ["5431:5432"]
    # volumes should be in alphabetical order 
    volumes: ["./sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql"]
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa